import { useState } from 'react';
import axios from 'axios';
import { useAuth } from '../context/AuthContext';
import './UploadWork.css';

export default function UploadWork({ onSuccess }) {
  const [name, setName] = useState('');
  const [description, setDescription] = useState('');
  const [imageFile, setImageFile] = useState(null);
  const [videoFile, setVideoFile] = useState(null);
  const [imagePreview, setImagePreview] = useState(null);
  const [videoPreview, setVideoPreview] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState(false);
  const { token } = useAuth();

  const handleImageChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      setImageFile(file);
      const objectUrl = URL.createObjectURL(file);
      // Only use blob: URLs generated by the browser (never arbitrary strings)
      if (objectUrl.startsWith('blob:')) {
        setImagePreview(objectUrl);
      }
    }
  };

  const handleVideoChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      setVideoFile(file);
      const objectUrl = URL.createObjectURL(file);
      // Only use blob: URLs generated by the browser (never arbitrary strings)
      if (objectUrl.startsWith('blob:')) {
        setVideoPreview(objectUrl);
      }
    }
  };

  const resetForm = () => {
    setName('');
    setDescription('');
    setImageFile(null);
    setVideoFile(null);
    if (imagePreview) URL.revokeObjectURL(imagePreview);
    if (videoPreview) URL.revokeObjectURL(videoPreview);
    setImagePreview(null);
    setVideoPreview(null);
    setError('');
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!name.trim()) {
      setError('Work name is required');
      return;
    }

    setLoading(true);
    setError('');
    setSuccess(false);

    try {
      const formData = new FormData();
      formData.append('name', name.trim());
      formData.append('description', description.trim());
      if (imageFile) formData.append('image', imageFile);
      if (videoFile) formData.append('video', videoFile);

      await axios.post('/api/works', formData, {
        headers: {
          Authorization: `Bearer ${token}`,
          'Content-Type': 'multipart/form-data',
        },
      });

      setSuccess(true);
      resetForm();
      setTimeout(() => {
        onSuccess && onSuccess();
      }, 1500);
    } catch (err) {
      setError(err.response?.data?.message || 'Failed to upload work. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="upload-container">
      <div className="upload-card">
        {success && (
          <div className="upload-success">
            ✅ Work uploaded successfully! Redirecting to portfolio…
          </div>
        )}
        {error && <div className="upload-error">⚠️ {error}</div>}

        <form onSubmit={handleSubmit} className="upload-form">
          <div className="form-row">
            <div className="form-group">
              <label htmlFor="work-name">
                Work Name <span className="required">*</span>
              </label>
              <input
                id="work-name"
                type="text"
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder="e.g. E-commerce Website"
                required
              />
            </div>
          </div>

          <div className="form-group">
            <label htmlFor="work-description">Description</label>
            <textarea
              id="work-description"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder="Describe this project…"
              rows={4}
            />
          </div>

          <div className="form-row two-cols">
            {/* Image upload */}
            <div className="form-group">
              <label>Image</label>
              <div className="file-drop-zone">
                {imagePreview ? (
                  <div className="preview-wrapper">
                    <img src={imagePreview} alt="Preview" className="preview-img" />
                    <button
                      type="button"
                      className="remove-preview"
                      onClick={() => { URL.revokeObjectURL(imagePreview); setImageFile(null); setImagePreview(null); }}
                    >
                      ✕
                    </button>
                  </div>
                ) : (
                  <label htmlFor="image-input" className="file-label">
                    <span>🖼️</span>
                    <span>Click to upload image</span>
                    <span className="file-hint">JPG, PNG, GIF, WEBP</span>
                  </label>
                )}
                <input
                  id="image-input"
                  type="file"
                  accept="image/*"
                  onChange={handleImageChange}
                  className="hidden-input"
                />
              </div>
            </div>

            {/* Video upload */}
            <div className="form-group">
              <label>Video</label>
              <div className="file-drop-zone">
                {videoPreview ? (
                  <div className="preview-wrapper">
                    <video src={videoPreview} controls className="preview-video" />
                    <button
                      type="button"
                      className="remove-preview"
                      onClick={() => { URL.revokeObjectURL(videoPreview); setVideoFile(null); setVideoPreview(null); }}
                    >
                      ✕
                    </button>
                  </div>
                ) : (
                  <label htmlFor="video-input" className="file-label">
                    <span>🎬</span>
                    <span>Click to upload video</span>
                    <span className="file-hint">MP4, WEBM, OGG, MOV (max 100 MB)</span>
                  </label>
                )}
                <input
                  id="video-input"
                  type="file"
                  accept="video/*"
                  onChange={handleVideoChange}
                  className="hidden-input"
                />
              </div>
            </div>
          </div>

          <div className="form-actions">
            <button type="button" className="cancel-btn" onClick={resetForm}>
              Clear Form
            </button>
            <button type="submit" className="submit-btn" disabled={loading}>
              {loading ? 'Uploading…' : '⬆️ Upload Work'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
